const TEAM_NAME_VI = {
  // World Cup / Euro / Đội tuyển quốc gia
  'Uruguay':           'Uruguay',
  'Germany':           'Đức',
  'Spain':             'Tây Ban Nha',
  'Paraguay':          'Paraguay',
  'Argentina':         'Argentina',
  'Ghana':             'Ghana',
  'Brazil':            'Brazil',
  'Portugal':          'Bồ Đào Nha',
  'Japan':             'Nhật Bản',
  'Slovakia':          'Slovakia',
  'Mexico':            'Mexico',
  'England':           'Anh',
  'United States':     'Mỹ',
  'South Korea':       'Hàn Quốc',
  'France':            'Pháp',
  'South Africa':      'Nam Phi',
  'Slovenia':          'Slovenia',
  'Algeria':           'Algeria',
  'Australia':         'Úc',
  'Serbia':            'Serbia',
  'Denmark':           'Đan Mạch',
  'New Zealand':       'New Zealand',
  'Italy':             'Ý',
  'Switzerland':       'Thụy Sĩ',
  'Ukraine':           'Ukraine',
  'Ecuador':           'Ecuador',
  'Sweden':            'Thụy Điển',
  'Poland':            'Ba Lan',
  'Czechia':           'Cộng hòa Séc',
  'Croatia':           'Croatia',
  'Saudi Arabia':      'Ả Rập Xê Út',
  'Tunisia':           'Tunisia',
  'Turkey':            'Thổ Nhĩ Kỳ',
  'Senegal':           'Senegal',
  'Belgium':           'Bỉ',
  'Romania':           'Romania',
  'Morocco':           'Ma-rốc',
  'Austria':           'Áo',
  'Colombia':          'Colombia',
  'Egypt':             'Ai Cập',
  'Hungary':           'Hungary',
  'Canada':            'Canada',
  'Haiti':             'Haiti',
  'Iran':              'Iran',
  'Bosnia-Herzegovina':'Bosnia & Herzegovina',
  'Albania':           'Albania',
  'Panama':            'Panama',
  'Cape Verde Islands':'Cape Verde',
  'Congo DR':          'CHDC Congo',
  'Ivory Coast':       'Bờ Biển Ngà',
  'Georgia':           'Georgia',
  'Qatar':             'Qatar',
  'Jordan':            'Jordan',
  'Iraq':              'Iraq',
  'Uzbekistan':        'Uzbekistan',
  'Netherlands':       'Hà Lan',
  'Norway':            'Na Uy',
  'Scotland':          'Scotland',
  'Curaçao':           'Curacao',

  // Premier League (EPL)
  'Arsenal FC':         'Arsenal',
  'Aston Villa FC':     'Aston Villa',
  'Chelsea FC':         'Chelsea',
  'Everton FC':         'Everton',
  'Fulham FC':          'Fulham',
  'Liverpool FC':       'Liverpool',
  'Manchester City FC': 'Man City',
  'Manchester United FC':'Man Utd',
  'Newcastle United FC':'Newcastle',
  'Sunderland AFC':     'Sunderland',
  'Tottenham Hotspur FC':'Tottenham',
  'Wolverhampton Wanderers FC': 'Wolves',
  'Burnley FC':         'Burnley',
  'Leicester City FC':  'Leicester City',
  'Southampton FC':     'Southampton',
  'Leeds United FC':    'Leeds Utd',
  'Watford':            'Watford',
  'Ipswich Town FC':    'Ipswich Town',
  'Nottingham Forest FC':'Nottingham Forest',
  'Crystal Palace FC':  'Crystal Palace',
  'Brighton & Hove Albion FC': 'Brighton',
  'Brentford FC':       'Brentford',
  'Fulham':             'Fulham',
  'West Ham United FC': 'West Ham',
  'Brighton & Hove Albion': 'Brighton',
  'AFC Bournemouth':    'Bournemouth',

  // Fallbacks
  'Manchester City':    'Man City',
  'Manchester United':  'Man Utd',
  'Tottenham Hotspur':  'Tottenham',
  'Newcastle United':   'Newcastle',
  'West Ham United':    'West Ham',
  'Wolverhampton':      'Wolves',
  'Sheffield United':   'Sheffield Utd',
  'Real Madrid':        'Real Madrid',
  'FC Barcelona':       'Barcelona',
  'Atletico Madrid':    'Atletico Madrid',
  'FC Bayern München':  'Bayern Munich',
  'Borussia Dortmund':  'Dortmund',
  'Juventus':           'Juventus',
  'Inter Milan':        'Inter Milan',
  'AC Milan':           'AC Milan',
  'Paris Saint-Germain':'PSG',
};

/**
 * Dịch tên đội bóng sang tiếng Việt (nếu có trong từ điển)
 */
export function toViName(name) {
  if (!name) return name;
  const cleanName = name.trim();
  return TEAM_NAME_VI[cleanName] || cleanName;
}
